# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Romain Ernandez
title: Software Engineer
email: romain.ernandez@gmail.com
# website: romain-ernandez.com

# Social links
# twitter_username: facespics
github_username: romainernandez
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: romainernandez
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/avataaars.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Romain and I'm a software engineer. I have experience in web application development as well as creating desktop ui and web sites.

  I am most skilled in: <mark>Python</mark> and <mark>Django</mark>

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Hiking
   - Running
   - Reading
   - Traveling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
